from pathlib import Path
import sys

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from app.core.security import hash_password
from app.db.database import SessionLocal
from app.models.user import User

SEED_USERS = [
    {
        "email": "arjun.mehta.manager@smartpos.demo",
        "username": "Arjun Mehta",
        "role": "manager",
        "password": "Manager@123",
    },
    {
        "email": "neha.verma.manager@smartpos.demo",
        "username": "Neha Verma",
        "role": "manager",
        "password": "Manager@123",
    },
    {
        "email": "rohit.patel.cashier@smartpos.demo",
        "username": "Rohit Patel",
        "role": "cashier",
        "password": "Cashier@123",
    },
    {
        "email": "priya.shah.cashier@smartpos.demo",
        "username": "Priya Shah",
        "role": "cashier",
        "password": "Cashier@123",
    },
    {
        "email": "aman.khan.cashier@smartpos.demo",
        "username": "Aman Khan",
        "role": "cashier",
        "password": "Cashier@123",
    },
]


def seed_users() -> None:
    db = SessionLocal()
    try:
        for entry in SEED_USERS:
            existing = db.query(User).filter(User.email == entry["email"]).first()
            if existing:
                existing.username = entry["username"]
                existing.role = entry["role"]
                existing.is_active = True
                existing.session_revoked = False
                existing.hashed_password = hash_password(entry["password"])
            else:
                db.add(
                    User(
                        email=entry["email"],
                        username=entry["username"],
                        role=entry["role"],
                        hashed_password=hash_password(entry["password"]),
                        is_active=True,
                        session_revoked=False,
                    )
                )
        db.commit()
    finally:
        db.close()


def write_credentials_file() -> Path:
    repo_root = Path(__file__).resolve().parents[2]
    output_path = repo_root / "seeded_user_credentials.txt"

    lines = [
        "SmartPOS Seeded Staff Credentials (Demo Use Only)",
        "Generated by backend/scripts/seed_staff_users.py",
        "",
    ]
    for idx, entry in enumerate(SEED_USERS, start=1):
        lines.append(f"{idx}. Role: {entry['role']}")
        lines.append(f"   Email: {entry['email']}")
        lines.append(f"   Username: {entry['username']}")
        lines.append(f"   Password: {entry['password']}")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


if __name__ == "__main__":
    seed_users()
    file_path = write_credentials_file()
    print(f"Seeded {len(SEED_USERS)} staff users")
    print(f"Credentials saved to: {file_path}")
